# openapi-function.yml
swagger: '2.0'
info:
  title: helloapi a simple API test
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
##TODO: Change this address to yous cloud function full path
        address: https://europe-west1-mscitqa.cloudfunctions.net/helloGET
      responses:
        '200':
          description: A successful response
          schema:
            type: string
