apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohttpk8s
spec:
  replicas: 3
  selector:
    matchLabels:
      run: sre-tester
  template:
    metadata:
      labels:
        run: sre-tester
    spec:
      containers:
      - name: gohttpserver
        image: eu.gcr.io/<YOUR PROJECT ID HERE>/go-http-sre-crash
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command: 
            - /bin/sh
            - -c
            - /app/restart.sh
          initialDelaySeconds: 3
          periodSeconds: 3

