apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gohpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gohttpk8s
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
