apiVersion: apps/v1
kind: Deployment
metadata:
  name: gohttpk8s
spec:
  replicas: 3
  selector:
    matchLabels:
      run: sre-tester
  template:
    metadata:
      labels:
        run: sre-tester
    spec:
      containers:
      - name: gohttpserver
        image: eu.gcr.io/it-quality-attributes-302610/go-http-sre-crash
        livenessProbe:
          httpGet:
            path: /getbalance
            port: 8080
            httpHeaders:
            - name: Web-Service-Up
              value: Test
          initialDelaySeconds: 3
          periodSeconds: 3        
